var CONFIRMATION_EMAIL_TEMPLATE = {
  subject: '{{EMAIL_TITLE}} #{{REGISTER_NUMBER}} - {{ABSENCE_DATE}}',

  textBody: [
    'Hola,',
    '',
    'Hem rebut {{ACTION_TEXT}} del teu Faltaré.',
    '',
    'Número de registre: {{REGISTER_NUMBER}}',
    'Data de registre: {{REGISTER_DATE}}',
    'Adreça electrònica: {{CREATOR_EMAIL}}',
    'Absència de: {{ABSENCE_TEACHER_NAME}}',
    'Data prevista de l\'absència: {{ABSENCE_DATE}}',
    'Absència de més d\'un dia?: {{MULTI_DAY}}',
    '{{REINCORPORATION_TEXT}}',
    'Professor acompanyant?: {{ACCOMPANYING_TEACHER}}',
    'Motiu: {{REASON}}',
    'Context: {{CONTEXT}}',
    '{{HOURS_TEXT}}',
    '{{RECOVERY_HOURS_TEXT}}',
    'Permís, llicència o absència ordinària: {{PERMIT_LICENSE_ABSENCE}}',
    '',
    'Classes seleccionades:',
    '{{SCHEDULE_TEXT}}',
    '',
    '{{MULTI_DAY_STUDENT_WORK_TEXT}}',
    '',
    'Recuperacions:',
    '{{RECOVERY_TEXT}}',
    '',
    'Document justificatiu:',
    '{{DOCUMENT_TEXT}}',
    '',
    'Guarda aquest correu com a referència.',
  ].join('\n'),

  htmlBody: [
    '<p>Hola,</p>',
    '<p>Hem rebut {{ACTION_TEXT_HTML}} del teu <strong>Faltaré</strong>.</p>',
    '<table cellpadding="6" cellspacing="0" style="border-collapse:collapse;border:1px solid #d7dde5;width:100%;max-width:760px;">',
    '{{SUMMARY_ROWS_HTML}}',
    '</table>',
    '<h3>Classes seleccionades</h3>',
    '{{SCHEDULE_HTML}}',
    '{{MULTI_DAY_STUDENT_WORK_HTML}}',
    '<h3>Recuperacions</h3>',
    '{{RECOVERY_HTML}}',
    '<h3>Document justificatiu</h3>',
    '{{DOCUMENT_HTML}}',
    '<p>Guarda aquest correu com a referència.</p>',
  ].join(''),
};
